### ISSUE TITLE
Quote doesn't seem to work if installed as a snap

### ISSUE THREAD

**Issue by frossm** [frossm/quoter#1]
symbol is always invalid.  Index throws errors.

**Comment by frossm** [comment]
Corrected.  I just don't have a great understanding of snaps yet.  I had to update the snapcraft.yaml file to allow the networking connector to work.

**Comment by tautme** [comment]
I seem to have the same problem. 
First installed from "ubuntu software" gui, then snap command line. 
Running ubuntu 20.04.2

**Comment by frossm** [comment]
Hello Tautme.  I just tried it and it seems to work on my Ubuntu 20..04.2 LTS.  This is a command line tool.  I installed via the snap command.  You do have to enter in the IEXCloud secret key per the [readme.md file](https://github.com/frossm/quoter#readme).  Can you try the following steps `highlighted` and let me know what is happening?

(You can ignore the formatting of the below, that's just GitHub)

`frosty@heimdall[~]$ sudo snap remove quoter`

`frosty@heimdall[~]$ sudo snap install quoter`
quoter 2.6.2 from Michael Fross installed

`frosty@heimdall[~]$ quoter -c`
Enter the IEXcloud.io Secret Token: 
PUT YOUR `sk_` TOKEN HERE
May 06, 2021 9:38:00 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
IEXCloud.io Secret Production Token Set To:   YourToken

`frosty@heimdall[~]$ quoter acn`

![image](https://user-images.githubusercontent.com/1618511/117319622-1aca9480-ae51-11eb-90b9-7f99a90f0b18.png)
