### ISSUE TITLE
Support flag to disable Index quotes

### ISSUE THREAD

**Issue by zakyvr** [frossm/quoter#4]
It would be great to have a flag that disables the fetching and display of the index quotes.

The requests to CNBC tend to timeout sporadically.

**Comment by frossm** [comment]
Hello zakyvr.  No worries, I can get that added.  I just looked this morning to see if IEXCloud would be supporting the DOW/NASDAQ/S&P quotes anytime soon.  It sounds like they will not.  I've been tempted to just use specific EFTs as a proxy to the actual index data which I can pull from IEXCloud, but that then it wouldn't be the actual data.  (DIA for the DOW, QQQ for the NASDAQ, and SPY for the S&P)

**Comment by frossm** [comment]
Hi.  Just added the `-n` switch which will disable the processing of the indexes.  I've just committed it to GitHub and created the v2.6.1 release.  If you use quoter as a snap it will take about an hour to create it in the edge channel.   If I don't hear any issues with it by tomorrow, I'll move it to production.

Please let me know if this solves your problem.

Michael
